[package]
name = "warp-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
warp = "0.3.2"
serde = {version="1", features = ["derive"]}
serde_json = "1"
tokio = {version="1.19", features=["macros", "rt", "rt-multi-thread"]}
